// next
import Head from 'next/head'

// styles
import 'styles/globals.css'

// types
import { AppProps } from 'next/app'
import { NextPage } from 'next'

const App: NextPage<AppProps> = ({ Component, pageProps }) => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
    </Head>

    <Component {...pageProps} />
  </>
)

export default App
